# /org/gnome/shell/extensions/

[paperwm]
animation-time=0.14999999999999991
cycle-height-steps=[0.33332999999999996, 0.5, 0.66666999999999998, 1.0]
cycle-width-steps=[0.33332999999999996, 0.5, 0.66666999999999998, 1.0]
gesture-horizontal-fingers=0
gesture-workspace-fingers=0
last-used-display-server='Wayland'
open-window-position=0
overview-ensure-viewport-animation=1
restore-attach-modal-dialogs='true'
restore-edge-tiling='true'
restore-keybinds='{"close":{"bind":"[\\"<Control><Super>f\\"]","schema_id":"org.gnome.desktop.wm.keybindings"},"move-to-monitor-left":{"bind":"[\\"<Super><Shift>Left\\"]","schema_id":"org.gnome.desktop.wm.keybindings"},"move-to-monitor-down":{"bind":"[\\"<Super><Shift>Down\\"]","schema_id":"org.gnome.desktop.wm.keybindings"},"show-desktop":{"bind":"[\\"<Primary><Super>d\\",\\"<Primary><Alt>d\\",\\"<Super>d\\"]","schema_id":"org.gnome.desktop.wm.keybindings"},"switch-applications":{"bind":"[\\"<Super>Tab\\",\\"<Alt>Tab\\"]","schema_id":"org.gnome.desktop.wm.keybindings"},"switch-to-workspace-left":{"bind":"[\\"<Super>Page_Up\\",\\"<Super><Alt>Left\\",\\"<Control><Alt>Left\\"]","schema_id":"org.gnome.desktop.wm.keybindings"},"switch-to-workspace-right":{"bind":"[\\"<Super>Page_Down\\",\\"<Super><Alt>Right\\",\\"<Control><Alt>Right\\"]","schema_id":"org.gnome.desktop.wm.keybindings"},"toggle-maximized":{"bind":"[\\"<Control><Super>d\\"]","schema_id":"org.gnome.desktop.wm.keybindings"},"move-to-monitor-right":{"bind":"[\\"<Super><Shift>Right\\"]","schema_id":"org.gnome.desktop.wm.keybindings"},"move-to-monitor-up":{"bind":"[\\"<Super><Shift>Up\\"]","schema_id":"org.gnome.desktop.wm.keybindings"},"shift-overview-up":{"bind":"[\\"<Super><Alt>Up\\"]","schema_id":"org.gnome.shell.keybindings"},"shift-overview-down":{"bind":"[\\"<Super><Alt>Down\\"]","schema_id":"org.gnome.shell.keybindings"}}'
restore-workspaces-only-on-primary='true'
show-focus-mode-icon=false
show-window-position-bar=false
show-workspace-indicator=false
window-gap=20

[paperwm/keybindings]
barf-out=['']
close-window=['<Control><Super>f']
cycle-height=['']
cycle-height-backwards=['']
cycle-width-backwards=['<Shift><Super>r']
live-alt-tab=['']
live-alt-tab-backward=['']
move-down=['']
move-down-workspace=['<Control><Super>k']
move-left=['<Control><Super>j']
move-monitor-above=['']
move-monitor-below=['']
move-monitor-left=['']
move-monitor-right=['']
move-previous-workspace=['']
move-previous-workspace-backward=['']
move-right=['<Control><Super>l']
move-up=['']
move-up-workspace=['<Control><Super>i']
new-window=['']
paper-toggle-fullscreen=['<Control><Super>d']
previous-workspace=['<Super>Tab']
previous-workspace-backward=['']
resize-h-dec=['']
resize-h-inc=['']
resize-w-dec=['']
resize-w-inc=['']
slurp-in=['']
switch-down=['']
switch-down-workspace=['']
switch-down-workspace-from-all-monitors=['<Super>k']
switch-first=['<Super>h']
switch-focus-mode=['']
switch-last=['<Super>semicolon']
switch-left=['<Super>j']
switch-next=['']
switch-previous=['']
switch-right=['<Super>l']
switch-up=['']
switch-up-workspace=['']
switch-up-workspace-from-all-monitors=['<Super>i']
take-window=['<Super>u']
toggle-maximize-width=['<Super>d']
toggle-scratch=['<Control><Super>BackSpace']
toggle-scratch-layer=['<Super>BackSpace']
toggle-scratch-window=['']
