# /org/gnome/settings-daemon/plugins/

[color]
night-light-enabled=true
night-light-schedule-automatic=true

[media-keys]
custom-keybindings=['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']
rotate-video-lock-static=['<Super>o', 'XF86RotationLockToggle']
screensaver=['<Control><Super>x']
terminal=['<Super>Return']

[media-keys/custom-keybindings/custom0]
binding='<Super>Return'
command='ptyxis --new-window'
name='Terminal'
