#!/usr/bin/env python3

import broadlink

for device in broadlink.xdiscover():
    device.auth()

    if device.mac == b'$\xdf\xa7\x99\xf6\xcd':
        # Small lamp
        device.set_state(pwr=1, brightness=30, colortemp=4600)
    else:
        # Big lamp
        device.set_state(pwr=1, brightness=95, colortemp=4600)
