set tabstop=2
set expandtab
set shiftwidth=2
set number
" set foldmethod=syntax

execute pathogen#infect()
syntax on
set background=dark
colorscheme PaperColor
filetype plugin indent on

let g:AutoPairsShortcutFastWrap = 'æ'
let g:user_emmet_mode='a'
let g:user_emmet_leader_key='<C-E>'
" auto remove trailing whitespace
" on save
autocmd BufWritePre * %s/\s\+$//e

let mapleader=" "
map <Leader>w :w<Enter>
map <Leader>q :q<Enter>

