set tabstop=2
set expandtab
set shiftwidth=2
set number
" set foldmethod=syntax

execute pathogen#infect()
syntax on
set background=dark
colorscheme PaperColor
filetype plugin indent on

let g:AutoPairsShortcutFastWrap = 'æ'
let g:user_emmet_mode='a'
let g:user_emmet_leader_key='<C-E>'
" auto remove trailing whitespace
" on save
autocmd BufWritePre * %s/\s\+$//e

let mapleader=" "
map <Leader>w :w<Enter>
map <Leader>q :q<Enter>

noremap <leader>1 1gt
noremap <leader>2 2gt
noremap <leader>3 3gt
noremap <leader>4 4gt
noremap <leader>5 5gt
noremap <leader>6 6gt
noremap <leader>7 7gt
noremap <leader>8 8gt
noremap <leader>9 9gt
noremap <leader>0 :tablast<cr>

noremap <leader>p :Files<Enter>
nnoremap <C-Left> :tabprevious<CR>
nnoremap <C-Right> :tabnext<CR>

