#!/usr/bin/env node
// Breadth first search of a project path. Requires the PROJECTS_HOME
// environment variable to be set.
const path = require("path");
const fs = require("fs").promises;
const IGNORED = [
  ".git",
  "node_modules",
  ".gradle",
  "dist",
  "lib",
  "e2e",
  "qmk_firmware",
];

const clean = (str) => str.replace(/[-_]g/, "");

const checkDir = async (dirname, query) => {
  const files = await fs.readdir(dirname, { withFileTypes: true });

  files.forEach((file) => {
    if (IGNORED.includes(file.name) || file.isFile()) {
      return;
    }

    const filePath = path.join(dirname, file.name);

    if (clean(file.name).includes(clean(query))) {
      console.log(filePath);
      process.exit();
    }

    checkDir(filePath, query);
  });
};

if (process.argv.length < 3) {
  console.error("No search argument specified");
  process.exit(1);
}

checkDir(process.env.PROJECTS_HOME, process.argv[2]);
