#!/bin/bash
#
# Log events from hyprland.
# Dependends on socat and jq.
#
#   Usage: hyprlisten [FILTER]
#

filter=${1}

function handle {
    # Remove everything including and after >>
    local event="${1/%>>*/}"

    # Remove everything including and before >>
    local value="${1/#*>>/}"

    # Show the event name if a filter was  not specified.
    if [[ -z "$filter" ]]; then
        # The event and value variables are not expanded intentionally.
        # shellcheck disable=SC2016
        stdbuf -o0 jq --null-input -cM \
            --arg event "$event" \
            --arg value "$value" \
            '{"event": $event, "value": $value}'
    fi

    # Do not return the name of the event if a filter was specified.
    if [[ "$event" == "$filter" ]]; then
        stdbuf -o0 echo "$value"
    fi
}

socat -u "UNIX-CONNECT:/tmp/hypr/${HYPRLAND_INSTANCE_SIGNATURE}/.socket2.sock" - |
    while read -r line; do
        handle "$line"
    done
