#!/bin/bash

config_dir=${XDG_CONFIG_HOME:-$HOME/.config}
profiles_dir="$config_dir/i3/profiles"

case $1 in
save)
    command="i3-resurrect save"
    ;;
restore)
    command="i3-resurrect restore"
    ;;
ls)
    ls "$profiles_dir"
    exit 0
    ;;
*)
    echo "Available options: save, restore, ls"
    exit 1
    ;;
esac

profile=$(ls "$profiles_dir" | "$HOME/.bin/rofi-input" "$1 profile" 5)
if [[ -z "$profile" ]]; then
    echo "no profile was specified"
    exit 1
fi

workspaces=(6 5 4 1 2 3)

for ws in "${workspaces[@]}"; do
    eval "$command --directory '$profiles_dir/$profile' -w $ws"
done
