# /org/gnome/

[mutter]
attach-modal-dialogs=false
dynamic-workspaces=false
edge-tiling=false
workspaces-only-on-primary=false

[shell]
disabled-extensions=['background-logo@fedorahosted.org', 'launch-new-instance@gnome-shell-extensions.gcampax.github.com', 'window-list@gnome-shell-extensions.gcampax.github.com', 'apps-menu@gnome-shell-extensions.gcampax.github.com']
enabled-extensions=['places-menu@gnome-shell-extensions.gcampax.github.com', 'paperwm@paperwm.github.com', 'appindicatorsupport@rgcjonas.gmail.com']
welcome-dialog-last-shown-version='49.1'
